POST http://localhost:4444/auth/register
Content-Type: application/json
 
 {
  "email": "test@example.com",
  "name": "Test User",
  "password": "securePassword123",
  "role": "",
  "sellerInfo": {"name": "Test Seller"},
  "buyerInfo": {}
}

###
POST http://localhost:4444/auth/login
Content-Type: application/json

{
  "email": "paulowniaptz07@gmail.com",
  "password": "234234"
}




###
POST  http://localhost:4444/categories
Content-Type: application/json
 
 {
  "name": "інвентар"
}

###
GET http://localhost:4444/categories
###
PATCH  http://localhost:4444/categories/680a48bc744395de768f5197
Content-Type: application/json

{
  "name": "растения"
}

###
DELETE http://localhost:4444/categories/680a4892744395de768f5193

###
GET  http://localhost:4444/trees

###
POST  http://localhost:4444/trees
Content-Type: application/json
 
 {
   "title": "дерево",
  "description": "Вічнозелене дерево, висота 2м",
  "price": 299,
  "imageUrl": "https://example.com/sosna.jpg",
  "category": "6627e8c86d6d3cc4b0fd8abc", 
  "stock": 10
}

###
DELETE http://localhost:4444/trees/680b8891d1cc6c807880efd9