POST http://localhost:4444/auth/register
Content-Type: application/json
 
 {
  "fullName": "Sam Derg",
  "email": "ajtjfwoxp@10mail.org",
  "password": "123123",
  "role": "",
  "sellerInfo": {},
  "buyerInfo": {}
}



###
POST http://localhost:4444/auth/request-password-reset
Content-Type: application/json

{
  "email": "andygrigs88@gmail.com"
}

###
POST http://localhost:4444/auth/reset-password
Content-Type: application/json

{
  "token": "PASTE_YOUR_TOKEN_HERE",
  "newPassword": "newpassword123"
}

###
POST http://localhost:4444/auth/login
Content-Type: application/json

{
  "email": "paulowniaptz07@gmail.com",
  "password": "234234"
}




###
POST http://localhost:4444/categories
Content-Type: application/json

{
  "name": {
    "ru": "Деревья",
    "ro": "Reitfs",
    "en": "Trees"
  }
}


###
GET http://localhost:4444/categories
###
PATCH  http://localhost:4444/categories/681a04dce29672505c925fe0
Content-Type: application/json

{
  "name": {
    "ru": "Деревья",
    "ro": "Actualizat Reitfs",
    "en": "Updated Trees"
  }
}

###
DELETE http://localhost:4444/categories/680b886ad1cc6c807880efd6




###
GET  http://localhost:4444/trees

###
POST  http://localhost:4444/trees
Content-Type: application/json
 
 {
   "title": "павлония",
  "description": "Вічнозелене дерево, висота 2м",
  "price": 299,
  "imageUrl": "https://example.com/sosna.jpg",
  "category": "680b886ad1cc6c807880efd6", 
  "stock": 10
}

###
PATCH  http://localhost:4444/trees/6818c1eabe407ca5739df1bd
Content-Type: application/json

{
  "category": "681aefe6224bf06198199221"
}
###
DELETE http://localhost:4444/trees/680b31f28784a4dbfd0f6710

###
DELETE http://localhost:4444/delete-image/1750406817953.jpeg