POST http://localhost:4444/auth/register
Content-Type: application/json
 
 {
  "email": "test@example.com",
  "name": "Test User",
  "password": "securePassword123",
  "role": "",
  "sellerInfo": {"name": "Test Seller"},
  "buyerInfo": {}
}


###
GET http://localhost:4444/